/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:9a17e301-63ac-4d8a-a1f8-7af452589f49",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_tfTdnR1Z1",
    //"aws_user_pools_id":"ap-south-1_ZpVeKVMgD",
    "aws_user_pools_web_client_id": "5n6n8doh36vjeji7jesvb5jcb7",
    "oauth": {}
};


export default awsmobile;
