const tree={
    "ADEN":{
        "role":"admin",
        "children":["BMY","BXA"],
        "username":"ADEN@gangmanagement.com"
    },
    "BMY":{
        "role":"incharge",
        "children":["BMYSECT1","BMYSECT2","BMYSECT3"],
        "username":"BMY@gangmanagement.com"
    },
    "BXA":{
        "role":"incharge",
        "children":["BXASECT1","BXASECT2","BXASECT3","BXASECT4"],
        "username":"BXA@gangmanagement.com"
    },
    "BMYSECT1":{
        "parent":"BMY",
        "role":"section",
        "children":["DTM29","DTM30","DTM31"],
        "username":"BMYSECT1@gangmanagement.com"
    },
    "BMYSECT2":{
        "parent":"BMY",
        "role":"section",
        "children":["DTM32","DTM33","DTM34"],
        "username":"BMYSECT2@gangmanagement.com"
    },
    "BMYSECT3":{
        "parent":"BMY",
        "role":"section",
        "children":["STOREGANG"],
        "username":"BMYSECT3@gangmanagement.com"
    },
    "BXASECT1":{
        "parent":"BXA",
        "role":"section",
        "children":["DTM19","DTM20","DTM21"],
        "username":"BXASECT1@gangmanagement.com"
    },
    "BXASECT2":{
        "parent":"BXA",
        "role":"section",
        "children":["DTM22","DTM23","DTM24"],
        "username":"BXASECT2@gangmanagement.com"
    },
    "BXASECT3":{
        "parent":"BXA",
        "role":"section",
        "children":["DTM25","DTM26","DTM27","DTM28"],
        "username":"BXASECT3@gangmanagement.com"
    },
    "BXASECT4":{
        "parent":"BXA",
        "role":"section",
        "children":["DRZKETIGANG"],
        "username":"BXASECT4@gangmanagement.com"
    },
    "OPENID":{
        "role":"open",
        "username":"OPENID@gangmanagement.com"
    }
    
}

export default tree;